POST http://localhost:8080/auth/register
Content-Type: application/json

{
	"email":"test@test24.com", 
	"password": "12345678",
	"name":"test"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
	"email":"test@test24.com", 
	"password": "123456789"
}

###

POST http://localhost:8080/user/update
Content-Type: application/json

{
	"name":"testeri2",
	"password":"123456789"
}

###

GET http://localhost:8080/user/retrieve
Content-Type: application/json

###

GET http://localhost:8080/auth/logout
Content-Type: application/json

###

POST http://localhost:8080/spends/
Content-Type: application/json

{
	"idArr":["60586bf127e9e21fdf89c433","60c764f0babbbc0babe9d664"]
}

###

POST http://localhost:8080/spends/add
Content-Type: application/json

{
	"category":"Travel",
	"cost":"1212",
	"currency":"$"
}

###