POST http://localhost:8080/auth/register
Content-Type: application/json

{
	"email":"test@test1.com", 
	"password": "12345678",
	"name":"test"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
	"email":"test@test.com", 
	"password": "123456789"
}

###

POST http://localhost:8080/user/update
Content-Type: application/json

{
	"name":"testeri2",
	"password":"123456789"
}

###

GET http://localhost:8080/user/retrieve
Content-Type: application/json

###

GET http://localhost:8080/auth/logout
Content-Type: application/json

###

POST http://localhost:8080/spends/
Content-Type: application/json

{
	"idArr":["60c7723ea2aca7192b6b045e","60c77264a2aca7192b6b0461"]
}

###

POST http://localhost:8080/spends/add
Content-Type: application/json

{
	"category":"Housing",
	"cost":"789",
	"currency":"$"
}

###